name: lint

on:
  push:
  pull_request:

jobs:
  ctxp_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Lint CTXP examples
        run: |
          python3 tools/ctxp_lint.py examples
